Use Images & Flavors from a compute using Java
MBonell/openstack-sdks-challenges pull request #2
Opened 2017-10-25 15:52 UTC by MarceStarlet

I forgot to do my pull-request since that last time when we try to do OpenStack meetup on the Java GDL, sorry for that. Now is a pleasure to contribute to this repo ❤️ 
Signed-off-by: MarceStarlet <marcestarlet@techwomen.org.mx>

2017-10-31 22:01 UTC, mbonell requested changes
Thanks Marce, can you please rename the folder and use "jclouds" since I'm using the name of the SDK as standard for all the examples folders

2018-11-01 19:23 UTC, MarceStarlet commented
Changes done, sorry for the super delay xD

2018-11-01 20:45 UTC, mbonell approved these changes

2018-11-01 20:45 UTC, MBonell commented
Thank you!

2018-11-01 20:47 UTC, merged